name: New Class Document Submission
description: Submit the document to be added to the list.
title: "New Class Document Submission"
labels: ["document-submission"]

body:
  - type: input
    id: name
    attributes:
      label: Document Name
      placeholder: Syllabus
    validations:
      required: true
      
  - type: input
    id: document_url
    attributes:
      label: Document URL
      placeholder: document.html
    validations:
      required: true
