name: Document Submission
description: Submit the document to be added to the list
title: "Document Submission"
labels: ["document-submission"]

body:
  - type: input
    id: name
    attributes:
      label: Document name
      placeholder: e.g., Office Hours
    validations:
      required: true
      
  - type: input
    id: document_url
    attributes:
      label: Document URL
      placeholder: e.g., officehours.html
    validations:
      required: true
